name: Monstera Publish

on:
  release:
    types: [created]

jobs:
  build:
    env:
      JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
      JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
      JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
      JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
      JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
      JRELEASER_MAVENCENTRAL_TOKEN: ${{ secrets.JRELEASER_MAVENCENTRAL_TOKEN }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Create Config
      uses: gradle/gradle-build-action@v3
      with:
        arguments: jreleaserConfig

    - name: Publish to local staging repo
      uses: gradle/gradle-build-action@v3
      with:
        arguments: publish

    - name: Release to Maven Central
      uses: gradle/gradle-build-action@v3
      with:
        arguments: jreleaserFullRelease